plugins {
    id 'com.android.application'
    id 'dagger.hilt.android.plugin'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'jacoco'
}

jacoco {
    toolVersion = '0.8.12'
}

android {
    def properties = new Properties()
    properties.load(new FileInputStream(rootProject.file("local.properties")))

    namespace 'com.example.androidperformanceoptimization'
    compileSdk 35
    packagingOptions { resources.excludes.add("META-INF/*") }


    defaultConfig {
        applicationId "com.example.androidperformanceoptimization"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }


    buildTypes {
        debug {
            resValue("string", "base_url","\"https://countriesnow.space/api/v0.1/\"")
//            resValue("string", "zomato_api_key", properties['zomatoapikey'])
            minifyEnabled false
            testCoverageEnabled true
        }

        release {
            resValue("string", "base_url","\"https://countriesnow.space/api/v0.1/\"")
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            //   resValue("string", "base_url", properties['baseurl'])
            //resValue("string", "zomato_api_key", properties['zomatoapikey'])
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }

    buildFeatures {
        dataBinding true
        compose true
    }

    testOptions {
        unitTests.all {
            jacoco {
                includeNoLocationClasses = true
                excludes = ['jdk.internal.*']
            }
        }
    }
}

tasks.register('jacocoDebugUnitTestReport', JacocoReport) {
    dependsOn 'testDebugUnitTest'

    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }

    def excludes = [
            '**/R.class',
            '**/R$*.class',
            '**/BuildConfig.*',
            '**/Manifest*.*',
            '**/*Test*.*',
            '**/android/databinding/**',
            '**/androidx/databinding/**',
            '**/BR.*',
            '**/*Binding.*',
            '**/*BindingImpl.*',
            '**/*_Factory.*',
            '**/*_MembersInjector.*',
            '**/*_HiltModules*.*',
            '**/*Hilt*.*',
            '**/Hilt_*.*',
            '**/Dagger*.*',
            '**/*Component*.*',
            '**/*Module*.*',
            '**/*ComposableSingletons*.*'
    ]

    classDirectories.setFrom(files([
            fileTree(dir: layout.buildDirectory.dir('intermediates/javac/debug/classes'), excludes: excludes),
            fileTree(dir: layout.buildDirectory.dir('tmp/kotlin-classes/debug'), excludes: excludes)
    ]))

    sourceDirectories.setFrom(files([
            'src/main/java'
    ]))

    executionData.setFrom(fileTree(dir: layout.buildDirectory, includes: [
            'jacoco/testDebugUnitTest.exec',
            'outputs/unit_test_code_coverage/debugUnitTest/testDebugUnitTest.exec'
    ]))
}


dependencies {
    implementation 'androidx.core:core-ktx:1.13.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.databinding:databinding-runtime:8.3.2'
    implementation 'androidx.test.ext:junit-ktx:1.3.0'
    implementation 'androidx.navigation:navigation-runtime-android:2.9.5'
    implementation 'androidx.compose.runtime:runtime-livedata:1.9.2'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.11.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0'
    implementation 'androidx.work:work-runtime-ktx:2.9.0'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0'
    implementation('androidx.lifecycle:lifecycle-runtime-ktx:2.7.0')
    implementation('androidx.lifecycle:lifecycle-livedata-ktx:2.7.0')

    // Room
    implementation 'androidx.room:room-runtime:2.6.1'
    kapt 'androidx.room:room-compiler:2.6.1'

    // Testing dependencies
    androidTestImplementation "junit:junit:4.13.2"
    androidTestImplementation 'androidx.test:core-ktx:1.5.0'
    androidTestImplementation 'androidx.test.ext:junit-ktx:1.1.5'
    androidTestImplementation 'androidx.test:rules:1.5.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    // Hilt
    def hilt_version="2.51.1"
    implementation "com.google.dagger:hilt-android:2.51.1"
    kapt "com.google.dagger:hilt-compiler:2.51.1"
    kapt 'androidx.hilt:hilt-compiler:1.2.0'


    // For instrumentation tests
    androidTestImplementation 'com.google.dagger:hilt-android-testing:2.51.1'
    androidTestAnnotationProcessor 'com.google.dagger:hilt-compiler:2.51.1'
    androidTestImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.8.0'
    androidTestImplementation 'androidx.arch.core:core-testing:2.2.0'
    //androidtestImplementation "org.mockito:mockito-core:2.25.0"
    //androidtestImplementation "org.mockito:mockito-inline:2.13.0"
    androidTestImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'

    // For local unit tests
    testImplementation 'com.google.dagger:hilt-android-testing:2.51.1'
    testAnnotationProcessor 'com.google.dagger:hilt-compiler:2.51.1'
    testImplementation 'org.mockito:mockito-core:5.11.0'
    testImplementation 'org.mockito:mockito-inline:5.2.0'
    testImplementation "androidx.arch.core:core-testing:2.2.0"

    // For Jetpack Compose
    implementation 'androidx.activity:activity-compose:1.8.0'
    implementation platform('androidx.compose:compose-bom:2024.09.00')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-graphics'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.material3:material3'
    androidTestImplementation platform('androidx.compose:compose-bom:2024.09.00')
    androidTestImplementation 'androidx.compose.ui:ui-test-junit4'
    debugImplementation 'androidx.compose.ui:ui-tooling'
    debugImplementation 'androidx.compose.ui:ui-test-manifest'
    implementation("androidx.navigation:navigation-compose:2.8.9")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.6.1")
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.8.0'
    testImplementation("org.robolectric:robolectric:4.13")
    implementation "org.jetbrains.kotlin:kotlin-test:2.0.21"
}

kapt {
    correctErrorTypes true
}

